// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKE_aRPBqov70mxfJ3eQx03upDtkcxQI',
    appId: '1:544307454373:android:14d89a62b16c1c6f33084c',
    messagingSenderId: '544307454373',
    projectId: 'newsapp-472fc',
    storageBucket: 'newsapp-472fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6AT5M_nn4QopZF89NDD935XoQ-PO8xfo',
    appId: '1:544307454373:ios:e761a47d16ce4fd933084c',
    messagingSenderId: '544307454373',
    projectId: 'newsapp-472fc',
    storageBucket: 'newsapp-472fc.appspot.com',
    androidClientId: '544307454373-i4n51lt43tvtmih6q8k1lfgn33g0eu3k.apps.googleusercontent.com',
    iosClientId: '544307454373-nni7q45pu283oikgbbu3920opb3v572q.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

}